### PR TITLE
Add profiling for each method called in CDEAPISession

### PR DESCRIPTION
**Pull request by TapasSenapati**
- Testing for capturing each methods timings
image
- Testing for successful session being logged
image

- Testing for failed run being logged
image

### CODE REVIEW

**Comment by tovganesh** [comment]
Hey why do we have .env checked in here? I though that was in .gitignore

**Comment by TapasSenapati** [comment]
Are we not checking this in code and only checkig in through a release ?

**Comment by tovganesh** [comment]
If we can refactor this code as discussed offline with moving out timer variables, it would be good to go.

**Review by tovganesh — APPROVED** [review]
looks good to me

**Pull request merged**
